ECS update
discourse/syslogstash pull request #7
Opened 2021-02-26 22:30 UTC by Supermathie

2021-02-26 22:31 UTC, Supermathie commented
the tests aren't going to pass as service_skeleton v2 doesn't yet exist 😸

2021-02-26 23:02 UTC, CvX requested changes

2021-02-26 23:02 UTC, CvX commented on Gemfile
> +gem 'thwait'
If this dependency is used it should be added to gemspec instead.
But I don't see `ThreadsWait` being used anywhere so it can probably be removed? 🤔

```suggestion
```

2021-02-26 23:51 UTC, Supermathie commented on Gemfile
> +gem 'thwait'
Weird; how did that get in there? It was supposed to be removed.

2021-03-01 15:30 UTC, Supermathie commented on Gemfile
> +gem 'thwait'
Ah I see; I think @danielwaterworth added it as he was trying something with it but ended up not using it and then then I removed it in a later commit?

We don't need this, right?

2021-03-01 15:58 UTC, Supermathie commented on Gemfile
> +gem 'thwait'
NVM - I see the usage of ThreadsWait was removed in 142d1cb35329b448e46d2a66cd8303dc4a98c8ac but the gem was never removed.

2021-03-01 16:21 UTC, CvX approved these changes

2021-03-01 16:24 UTC, merged